# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'
use_frameworks! :linkage => :static

target 'BinaryDemo' do
  pod 'BINARY_NAME', 'BINARY_VERSION'
end
